# Generated by Django 5.0.7 on 2025-10-19 14:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEnhancementSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plagiarism_threshold', models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('plagiarism_notifications', models.BooleanField(default=True)),
                ('grammar_language', models.CharField(default='en', max_length=10)),
                ('grammar_notifications', models.BooleanField(default=True)),
                ('topic_suggestion_count', models.IntegerField(default=5)),
                ('topic_suggestion_notifications', models.BooleanField(default=True)),
                ('auto_processing', models.BooleanField(default=False)),
                ('cost_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_enhancement_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Enhancement Settings',
                'verbose_name_plural': 'AI Enhancement Settings',
                'db_table': 'ai_enhancement_settings',
            },
        ),
        migrations.CreateModel(
            name='GrammarCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('text', 'Text Check'), ('document', 'Document Check'), ('code', 'Code Check')], max_length=20)),
                ('text_content', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_errors', models.IntegerField(default=0)),
                ('total_suggestions', models.IntegerField(default=0)),
                ('grammar_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_checks', to='projects.projectgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grammar Check',
                'verbose_name_plural': 'Grammar Checks',
                'db_table': 'grammar_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(choices=[('grammar', 'Grammar Error'), ('spelling', 'Spelling Error'), ('punctuation', 'Punctuation Error'), ('style', 'Style Error'), ('clarity', 'Clarity Error')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('original_text', models.TextField()),
                ('suggested_text', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grammar_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='ai_enhancement.grammarcheck')),
            ],
            options={
                'verbose_name': 'Grammar Error',
                'verbose_name_plural': 'Grammar Errors',
                'db_table': 'grammar_errors',
                'ordering': ['start_position'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('document', 'Document Check'), ('code', 'Code Check'), ('text', 'Text Check')], max_length=20)),
                ('document_name', models.CharField(max_length=255)),
                ('document_content', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('similarity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_plagiarized', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks', to='projects.projectgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plagiarism Check',
                'verbose_name_plural': 'Plagiarism Checks',
                'db_table': 'plagiarism_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=500)),
                ('source_title', models.CharField(max_length=255)),
                ('similarity_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('matched_text', models.TextField()),
                ('context_before', models.TextField(blank=True, null=True)),
                ('context_after', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plagiarism_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ai_enhancement.plagiarismcheck')),
            ],
            options={
                'verbose_name': 'Plagiarism Match',
                'verbose_name_plural': 'Plagiarism Matches',
                'db_table': 'plagiarism_matches',
                'ordering': ['-similarity_percentage'],
            },
        ),
        migrations.CreateModel(
            name='TopicSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('research', 'Research Topic'), ('thesis', 'Thesis Topic'), ('project', 'Project Topic'), ('paper', 'Paper Topic')], max_length=20)),
                ('user_input', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('confidence_scores', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_suggestions', to='projects.projectgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Suggestion',
                'verbose_name_plural': 'Topic Suggestions',
                'db_table': 'topic_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicSimilarity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similar_topic', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('source', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='ai_enhancement.topicsuggestion')),
            ],
            options={
                'verbose_name': 'Topic Similarity',
                'verbose_name_plural': 'Topic Similarities',
                'db_table': 'ai_enhancement_topic_similarities',
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='AIEnhancementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('plagiarism', 'Plagiarism Check'), ('grammar', 'Grammar Check'), ('topic', 'Topic Suggestion'), ('similarity', 'Topic Similarity')], max_length=20)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('processing_time', models.FloatField()),
                ('tokens_used', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_enhancement_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Enhancement Log',
                'verbose_name_plural': 'AI Enhancement Logs',
                'db_table': 'ai_enhancement_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_enhancem_user_id_6c2998_idx'), models.Index(fields=['service_type'], name='ai_enhancem_service_28bb86_idx'), models.Index(fields=['success'], name='ai_enhancem_success_a5a728_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='grammarcheck',
            index=models.Index(fields=['user', 'created_at'], name='grammar_che_user_id_93f4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarcheck',
            index=models.Index(fields=['project', 'created_at'], name='grammar_che_project_e0bd79_idx'),
        ),
        migrations.AddIndex(
            model_name='grammarcheck',
            index=models.Index(fields=['status'], name='grammar_che_status_01f6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismcheck',
            index=models.Index(fields=['user', 'created_at'], name='plagiarism__user_id_64f7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismcheck',
            index=models.Index(fields=['project', 'created_at'], name='plagiarism__project_8d167b_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismcheck',
            index=models.Index(fields=['status'], name='plagiarism__status_a3bbad_idx'),
        ),
        migrations.AddIndex(
            model_name='topicsuggestion',
            index=models.Index(fields=['user', 'created_at'], name='topic_sugge_user_id_47d0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='topicsuggestion',
            index=models.Index(fields=['project', 'created_at'], name='topic_sugge_project_133ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='topicsuggestion',
            index=models.Index(fields=['status'], name='topic_sugge_status_fbe9b2_idx'),
        ),
    ]
