# Generated by Django 5.0.7 on 2025-10-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='student',
            name='expected_graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicrecord',
            name='credits_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='achievement_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='date_earned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='class_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='note_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
    ]
