# Generated by Django 5.0.7 on 2025-10-19 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbreviation', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('degree_level', models.CharField(default='Bachelor', max_length=50)),
                ('duration_years', models.IntegerField(default=4)),
                ('total_credits', models.IntegerField(default=120)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('faculty', models.CharField(blank=True, max_length=200, null=True)),
                ('head_of_department', models.CharField(blank=True, max_length=200, null=True)),
                ('office_location', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
                'db_table': 'majors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MajorCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=3)),
                ('course_type', models.CharField(default='core', max_length=50)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='majors.major')),
            ],
            options={
                'verbose_name': 'Major Curriculum',
                'verbose_name_plural': 'Major Curriculum',
                'db_table': 'major_curriculum',
                'ordering': ['year', 'semester', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='MajorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('academic', 'Academic Note'), ('administrative', 'Administrative Note'), ('general', 'General Note')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='majors.major')),
            ],
            options={
                'verbose_name': 'Major Note',
                'verbose_name_plural': 'Major Notes',
                'db_table': 'major_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MajorRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('credits', models.IntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='majors.major')),
            ],
            options={
                'verbose_name': 'Major Requirement',
                'verbose_name_plural': 'Major Requirements',
                'db_table': 'major_requirements',
                'ordering': ['requirement_type', 'description'],
            },
        ),
    ]
