# Generated by Django 5.0.7 on 2025-10-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majornote',
            name='major',
        ),
        migrations.AlterModelOptions(
            name='majorrequirement',
            options={'ordering': ['major', 'requirement_type'], 'verbose_name': 'Major Requirement', 'verbose_name_plural': 'Major Requirements'},
        ),
        migrations.RemoveField(
            model_name='major',
            name='department',
        ),
        migrations.RemoveField(
            model_name='major',
            name='duration_years',
        ),
        migrations.RemoveField(
            model_name='major',
            name='email',
        ),
        migrations.RemoveField(
            model_name='major',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='major',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='major',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='major',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='major',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='major',
            name='total_credits',
        ),
        migrations.RemoveField(
            model_name='majorrequirement',
            name='credits',
        ),
        migrations.AddField(
            model_name='majorrequirement',
            name='requirement_value',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='majorrequirement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MajorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='majors.major')),
            ],
            options={
                'verbose_name': 'Major Specialization',
                'verbose_name_plural': 'Major Specializations',
                'db_table': 'major_specializations',
                'ordering': ['major', 'name'],
                'unique_together': {('major', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='MajorCurriculum',
        ),
        migrations.DeleteModel(
            name='MajorNote',
        ),
    ]
