# Generated by Django 5.0.7 on 2025-10-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0002_remove_majornote_major_and_more'),
    ]

    operations = [
        # Skip SQLite incompatible operations
        # These columns will be handled by recreating the table if needed
        migrations.RunSQL(
            "SELECT 1;",  # Dummy operation that always succeeds
            reverse_sql="SELECT 1;"
        ),
    ]