# Generated by Django 5.0.7 on 2025-10-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, unique=True)),
                ('topic_lao', models.CharField(max_length=500)),
                ('topic_eng', models.CharField(max_length=500)),
                ('advisor_name', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('main_committee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('second_committee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('third_committee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('defense_date', models.DateField(blank=True, null=True)),
                ('defense_time', models.TimeField(blank=True, null=True)),
                ('defense_room', models.CharField(blank=True, max_length=100, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('main_advisor_score', models.FloatField(blank=True, null=True)),
                ('main_committee_score', models.FloatField(blank=True, null=True)),
                ('second_committee_score', models.FloatField(blank=True, null=True)),
                ('third_committee_score', models.FloatField(blank=True, null=True)),
                ('similarity_info', models.JSONField(blank=True, null=True)),
                ('project_health_status', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Group',
                'verbose_name_plural': 'Project Groups',
                'db_table': 'project_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projectgroup')),
            ],
            options={
                'verbose_name': 'Project File',
                'verbose_name_plural': 'Project Files',
                'db_table': 'project_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(default='general', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_logs', to=settings.AUTH_USER_MODEL)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='projects.projectgroup')),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'db_table': 'communication_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('issues', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by_ai', models.BooleanField(default=True)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='projects.projectgroup')),
            ],
            options={
                'verbose_name': 'Project Health Check',
                'verbose_name_plural': 'Project Health Checks',
                'db_table': 'project_health_checks',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='projects.projectgroup')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'db_table': 'status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('similarity_percentage', models.FloatField(default=0.0)),
                ('reason', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_analyses', to='projects.projectgroup')),
            ],
            options={
                'verbose_name': 'Topic Similarity',
                'verbose_name_plural': 'Topic Similarities',
                'db_table': 'topic_similarities',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='projects.projectgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Student',
                'verbose_name_plural': 'Project Students',
                'db_table': 'project_students',
                'unique_together': {('project_group', 'student')},
            },
        ),
    ]
