# Generated by Django 5.0.7 on 2025-10-20 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('event', 'Event'), ('comment', 'Comment'), ('status_change', 'Status Change'), ('file_upload', 'File Upload'), ('defense_scheduled', 'Defense Scheduled')], max_length=20)),
                ('author_id', models.IntegerField()),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='projects.projectgroup')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'project_log_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='project_log_project_958a6f_idx'), models.Index(fields=['type'], name='project_log_type_12ee1c_idx')],
            },
        ),
    ]
