# Generated by Django 5.0.7 on 2025-10-19 14:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_duration', models.IntegerField(default=60)),
                ('max_duration', models.IntegerField(default=120)),
                ('min_duration', models.IntegerField(default=30)),
                ('pass_threshold', models.FloatField(default=70.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('conditional_pass_threshold', models.FloatField(default=60.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('send_reminders', models.BooleanField(default=True)),
                ('reminder_days', models.IntegerField(default=7)),
                ('send_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Defense Settings',
                'verbose_name_plural': 'Defense Settings',
                'db_table': 'defense_settings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DefenseRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('conference', 'Conference Room'), ('auditorium', 'Auditorium'), ('lab', 'Laboratory'), ('online', 'Online')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Defense Room',
                'verbose_name_plural': 'Defense Rooms',
                'db_table': 'defense_rooms',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['room_type'], name='defense_roo_room_ty_e39bd8_idx'), models.Index(fields=['is_available'], name='defense_roo_is_avai_db7b2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DefenseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('defense_date', models.DateTimeField()),
                ('defense_time', models.TimeField()),
                ('defense_room', models.CharField(max_length=100)),
                ('defense_duration', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_defense_schedules', to=settings.AUTH_USER_MODEL)),
                ('main_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_committee_defenses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_schedules', to='projects.projectgroup')),
                ('second_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_committee_defenses', to=settings.AUTH_USER_MODEL)),
                ('third_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_committee_defenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Defense Schedule',
                'verbose_name_plural': 'Defense Schedules',
                'db_table': 'defense_schedules',
                'ordering': ['defense_date', 'defense_time'],
            },
        ),
        migrations.CreateModel(
            name='DefenseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('scheduled', 'Defense Scheduled'), ('started', 'Defense Started'), ('completed', 'Defense Completed'), ('cancelled', 'Defense Cancelled'), ('postponed', 'Defense Postponed'), ('evaluation', 'Evaluation Submitted'), ('result', 'Result Decided')], max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_logs', to=settings.AUTH_USER_MODEL)),
                ('defense_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='defense_management.defenseschedule')),
            ],
            options={
                'verbose_name': 'Defense Log',
                'verbose_name_plural': 'Defense Logs',
                'db_table': 'defense_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefenseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('pre_defense', 'Pre-Defense'), ('final_defense', 'Final Defense'), ('revision', 'Revision Defense')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('session_notes', models.TextField(blank=True, null=True)),
                ('committee_notes', models.TextField(blank=True, null=True)),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defense_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='defense_management.defenseschedule')),
            ],
            options={
                'verbose_name': 'Defense Session',
                'verbose_name_plural': 'Defense Sessions',
                'db_table': 'defense_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefenseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('pass', 'Pass'), ('conditional_pass', 'Conditional Pass'), ('fail', 'Fail'), ('incomplete', 'Incomplete')], max_length=20)),
                ('total_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_possible_score', models.FloatField(default=100.0)),
                ('committee_decision', models.TextField()),
                ('committee_recommendations', models.TextField(blank=True, null=True)),
                ('revision_requirements', models.TextField(blank=True, null=True)),
                ('final_decision', models.CharField(choices=[('pass', 'Pass'), ('conditional_pass', 'Conditional Pass'), ('fail', 'Fail'), ('incomplete', 'Incomplete')], max_length=20)),
                ('final_decision_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_decision_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_defense_decisions', to=settings.AUTH_USER_MODEL)),
                ('defense_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='defense_management.defensesession')),
            ],
            options={
                'verbose_name': 'Defense Result',
                'verbose_name_plural': 'Defense Results',
                'db_table': 'defense_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefenseEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_type', models.CharField(choices=[('presentation', 'Presentation'), ('content', 'Content'), ('methodology', 'Methodology'), ('results', 'Results'), ('discussion', 'Discussion'), ('overall', 'Overall')], max_length=20)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_score', models.FloatField(default=100.0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_evaluations', to=settings.AUTH_USER_MODEL)),
                ('defense_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='defense_management.defensesession')),
            ],
            options={
                'verbose_name': 'Defense Evaluation',
                'verbose_name_plural': 'Defense Evaluations',
                'db_table': 'defense_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='defenseschedule',
            index=models.Index(fields=['defense_date'], name='defense_sch_defense_eeac76_idx'),
        ),
        migrations.AddIndex(
            model_name='defenseschedule',
            index=models.Index(fields=['status'], name='defense_sch_status_9f1cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='defenseschedule',
            index=models.Index(fields=['project'], name='defense_sch_project_064405_idx'),
        ),
        migrations.AddIndex(
            model_name='defenselog',
            index=models.Index(fields=['defense_schedule', 'created_at'], name='defense_log_defense_0edc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='defenselog',
            index=models.Index(fields=['log_type'], name='defense_log_log_typ_37b211_idx'),
        ),
        migrations.AddIndex(
            model_name='defenselog',
            index=models.Index(fields=['user'], name='defense_log_user_id_63c24a_idx'),
        ),
        migrations.AddIndex(
            model_name='defensesession',
            index=models.Index(fields=['defense_schedule', 'session_type'], name='defense_ses_defense_74b22c_idx'),
        ),
        migrations.AddIndex(
            model_name='defensesession',
            index=models.Index(fields=['status'], name='defense_ses_status_6cfa9d_idx'),
        ),
        migrations.AddIndex(
            model_name='defenseresult',
            index=models.Index(fields=['result_type'], name='defense_res_result__265be7_idx'),
        ),
        migrations.AddIndex(
            model_name='defenseresult',
            index=models.Index(fields=['final_decision'], name='defense_res_final_d_be58f5_idx'),
        ),
        migrations.AddIndex(
            model_name='defenseevaluation',
            index=models.Index(fields=['defense_session', 'evaluator'], name='defense_eva_defense_bb058d_idx'),
        ),
        migrations.AddIndex(
            model_name='defenseevaluation',
            index=models.Index(fields=['evaluation_type'], name='defense_eva_evaluat_9a8f98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='defenseevaluation',
            unique_together={('defense_session', 'evaluator', 'evaluation_type')},
        ),
    ]
