# Generated by Django 5.0.7 on 2025-10-19 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(default='2024-2025', max_length=10)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(default=30)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='majors.major')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'classrooms',
                'ordering': ['name'],
                'unique_together': {('name', 'major', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('maintenance', 'Maintenance Note'), ('equipment', 'Equipment Note'), ('general', 'General Note')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='classrooms.classroom')),
            ],
            options={
                'verbose_name': 'Classroom Note',
                'verbose_name_plural': 'Classroom Notes',
                'db_table': 'classroom_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_by', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='classrooms.classroom')),
            ],
            options={
                'verbose_name': 'Classroom Reservation',
                'verbose_name_plural': 'Classroom Reservations',
                'db_table': 'classroom_reservations',
                'ordering': ['-reservation_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=200)),
                ('instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classrooms.classroom')),
            ],
            options={
                'verbose_name': 'Classroom Schedule',
                'verbose_name_plural': 'Classroom Schedules',
                'db_table': 'classroom_schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
