# Generated by Django 5.0.7 on 2025-10-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, remove the problematic models
        migrations.DeleteModel(
            name='ClassroomNote',
        ),
        migrations.DeleteModel(
            name='ClassroomReservation',
        ),
        
        # Update model options
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['major', 'name'], 'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='classroomschedule',
            options={'ordering': ['classroom', 'day_of_week', 'start_time'], 'verbose_name': 'Classroom Schedule', 'verbose_name_plural': 'Classroom Schedules'},
        ),
        
        # Remove fields that are no longer needed
        migrations.RemoveField(
            model_name='classroom',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='classroomschedule',
            name='is_active',
        ),
        
        # Add new fields to classroom model
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        
        # Update existing fields
        migrations.AlterField(
            model_name='classroom',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classroomschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classroomschedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        
        # Update unique constraints (do this after adding the semester field)
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'academic_year', 'semester')},
        ),
        
        # Create new model for classroom-student relationship
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classrooms.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom Student',
                'verbose_name_plural': 'Classroom Students',
                'db_table': 'classroom_students',
                'ordering': ['classroom', 'student'],
                'unique_together': {('classroom', 'student')},
            },
        ),
    ]