# Generated by Django 5.0.7 on 2025-10-19 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField(default=30)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Milestone Template',
                'verbose_name_plural': 'Milestone Templates',
                'db_table': 'milestone_templates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.projectgroup')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='milestones.milestonetemplate')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'db_table': 'milestones',
                'ordering': ['due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('feedback', 'Feedback Note'), ('general', 'General Note')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_notes', to='milestones.milestone')),
            ],
            options={
                'verbose_name': 'Milestone Note',
                'verbose_name_plural': 'Milestone Notes',
                'db_table': 'milestone_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
                ('message', models.TextField()),
                ('recipients', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='milestones.milestone')),
            ],
            options={
                'verbose_name': 'Milestone Reminder',
                'verbose_name_plural': 'Milestone Reminders',
                'db_table': 'milestone_reminders',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('review_score', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='milestones.milestone')),
            ],
            options={
                'verbose_name': 'Milestone Submission',
                'verbose_name_plural': 'Milestone Submissions',
                'db_table': 'milestone_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_by', models.CharField(max_length=200)),
                ('provided_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_type', models.CharField(default='general', max_length=50)),
                ('content', models.TextField()),
                ('is_constructive', models.BooleanField(default=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='milestones.milestonesubmission')),
            ],
            options={
                'verbose_name': 'Milestone Feedback',
                'verbose_name_plural': 'Milestone Feedback',
                'db_table': 'milestone_feedback',
                'ordering': ['-provided_at'],
            },
        ),
    ]
