# Generated by Django 5.0.7 on 2025-10-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonenote',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='milestonereminder',
            name='milestone',
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['project_group', 'due_date'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AlterModelOptions(
            name='milestonetemplate',
            options={'ordering': ['name'], 'verbose_name': 'Milestone Template', 'verbose_name_plural': 'Milestone Templates'},
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='approval_notes',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='review_score',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='title',
        ),
        migrations.RemoveField(
            model_name='milestonesubmission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='milestonetemplate',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='milestonetemplate',
            name='order',
        ),
        migrations.AddField(
            model_name='milestone',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='feedback_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='submitted_file',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestonesubmission',
            name='file_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='milestonesubmission',
            name='submission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='estimated_duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('RequiresRevision', 'Requires Revision')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.milestonetemplate'),
        ),
        migrations.AlterField(
            model_name='milestonesubmission',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='milestonesubmission',
            name='file_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='milestonesubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MilestoneReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_notes', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(default=100.0)),
                ('criteria_scores', models.JSONField(default=dict)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='milestones.milestone')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone Review',
                'verbose_name_plural': 'Milestone Reviews',
                'db_table': 'milestone_reviews',
                'ordering': ['-reviewed_at'],
                'unique_together': {('milestone', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default=7)),
                ('order', models.IntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='milestones.milestonetemplate')),
            ],
            options={
                'verbose_name': 'Milestone Task',
                'verbose_name_plural': 'Milestone Tasks',
                'db_table': 'milestone_tasks',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='MilestoneFeedback',
        ),
        migrations.DeleteModel(
            name='MilestoneNote',
        ),
        migrations.DeleteModel(
            name='MilestoneReminder',
        ),
    ]
