# Generated by Django 5.0.7 on 2025-10-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_remove_milestonenote_milestone_and_more'),
    ]

    operations = [
    ]
