# Generated by Django 5.0.7 on 2025-10-19 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('committee_type', models.CharField(choices=[('main', 'Main Committee'), ('second', 'Second Committee'), ('third', 'Third Committee')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('established_date', models.DateField(default=django.utils.timezone.now)),
                ('dissolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='committee_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'db_table': 'committees',
                'ordering': ['committee_id'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('main', 'Main Committee'), ('second', 'Second Committee'), ('third', 'Third Committee')], max_length=20)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('evaluation_time', models.TimeField(blank=True, null=True)),
                ('evaluation_room', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='committees.committee')),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_assignments', to='projects.projectgroup')),
            ],
            options={
                'verbose_name': 'Committee Assignment',
                'verbose_name_plural': 'Committee Assignments',
                'db_table': 'committee_assignments',
                'ordering': ['-assigned_date'],
                'unique_together': {('project_group', 'committee', 'assignment_type')},
            },
        ),
        migrations.CreateModel(
            name='CommitteeMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('meeting_room', models.CharField(max_length=100)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('minutes', models.TextField(blank=True, null=True)),
                ('decisions', models.TextField(blank=True, null=True)),
                ('action_items', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='committee_meetings', to=settings.AUTH_USER_MODEL)),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_meetings', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='committees.committee')),
            ],
            options={
                'verbose_name': 'Committee Meeting',
                'verbose_name_plural': 'Committee Meetings',
                'db_table': 'committee_meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('meeting', 'Meeting Note'), ('evaluation', 'Evaluation Note'), ('general', 'General Note')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='committees.committee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Note',
                'verbose_name_plural': 'Committee Notes',
                'db_table': 'committee_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.FloatField(default=0.0)),
                ('presentation_score', models.FloatField(default=0.0)),
                ('documentation_score', models.FloatField(default=0.0)),
                ('innovation_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('overall_comments', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='committees.committeeassignment')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Evaluation',
                'verbose_name_plural': 'Committee Evaluations',
                'db_table': 'committee_evaluations',
                'ordering': ['-evaluated_at'],
                'unique_together': {('assignment', 'evaluator')},
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='member', max_length=50)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('expertise_areas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='committees.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'db_table': 'committee_members',
                'ordering': ['-joined_date'],
                'unique_together': {('committee', 'member')},
            },
        ),
    ]
