# Generated by Django 5.0.7 on 2025-10-19 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rubric_type', models.CharField(default='advisor', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scoring Rubric',
                'verbose_name_plural': 'Scoring Rubrics',
                'db_table': 'scoring_rubrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(max_length=200)),
                ('evaluator_id', models.CharField(max_length=50)),
                ('total_score', models.FloatField(default=0.0)),
                ('max_possible_score', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('is_final', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='projects.projectgroup')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scoring.scoringrubric')),
            ],
            options={
                'verbose_name': 'Project Score',
                'verbose_name_plural': 'Project Scores',
                'db_table': 'project_scores',
                'ordering': ['-created_at'],
                'unique_together': {('project_group', 'rubric', 'evaluator_id')},
            },
        ),
        migrations.CreateModel(
            name='ScoringAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_score', models.FloatField(blank=True, null=True)),
                ('new_score', models.FloatField(blank=True, null=True)),
                ('changed_by', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('project_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='scoring.projectscore')),
            ],
            options={
                'verbose_name': 'Scoring Audit',
                'verbose_name_plural': 'Scoring Audit',
                'db_table': 'scoring_audit',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('evaluation', 'Evaluation Note'), ('feedback', 'Feedback Note'), ('general', 'General Note')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scoring.projectscore')),
            ],
            options={
                'verbose_name': 'Scoring Note',
                'verbose_name_plural': 'Scoring Notes',
                'db_table': 'scoring_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_score', models.FloatField()),
                ('weight', models.FloatField(default=1.0)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scoring.scoringrubric')),
            ],
            options={
                'verbose_name': 'Scoring Rubric Item',
                'verbose_name_plural': 'Scoring Rubric Items',
                'db_table': 'scoring_rubric_items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='scoring.projectscore')),
                # ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_details', to='scoring.scoringrubricitem')),
            ],
            options={
                'verbose_name': 'Project Score Detail',
                'verbose_name_plural': 'Project Score Details',
                'db_table': 'project_score_details',
                # 'ordering': ['rubric_item__order'],
                # 'unique_together': {('project_score', 'rubric_item')},
            },
        ),
        migrations.CreateModel(
            name='ScoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2024-2025', max_length=10)),
                ('advisor_weight', models.FloatField(default=0.4)),
                ('committee_weight', models.FloatField(default=0.6)),
                ('a_grade_min', models.FloatField(default=90.0)),
                ('b_grade_min', models.FloatField(default=80.0)),
                ('c_grade_min', models.FloatField(default=70.0)),
                ('d_grade_min', models.FloatField(default=60.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_settings', to='scoring.scoringrubric')),
                ('committee_rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_settings', to='scoring.scoringrubric')),
            ],
            options={
                'verbose_name': 'Scoring Settings',
                'verbose_name_plural': 'Scoring Settings',
                'db_table': 'scoring_settings',
                'ordering': ['-academic_year'],
                'unique_together': {('academic_year',)},
            },
        ),
    ]
