# Generated by Django 5.0.7 on 2025-10-19 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, create new models
        migrations.CreateModel(
            name='ScoringCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight', models.FloatField(help_text='Weight as percentage (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_score', models.FloatField(default=100.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scoring Criteria',
                'verbose_name_plural': 'Scoring Criteria',
                'db_table': 'scoring_criteria',
                'ordering': ['weight', 'name'],
            },
        ),
        
        migrations.CreateModel(
            name='DefenseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_score', models.FloatField(help_text='Presentation quality (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('technical_score', models.FloatField(help_text='Technical content (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('qa_score', models.FloatField(help_text='Q&A performance (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_scores', to='projects.projectgroup')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Defense Score',
                'verbose_name_plural': 'Defense Scores',
                'db_table': 'defense_scores',
                'ordering': ['-scored_at'],
                'unique_together': {('project_group', 'scorer')},
            },
        ),
        
        migrations.CreateModel(
            name='ScoringRubricCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight within this rubric (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.scoringcriteria')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='scoring.scoringrubric')),
            ],
            options={
                'verbose_name': 'Scoring Rubric Criteria',
                'verbose_name_plural': 'Scoring Rubric Criteria',
                'db_table': 'scoring_rubric_criteria',
                'ordering': ['rubric', 'order'],
                'unique_together': {('rubric', 'criteria')},
            },
        ),
        
        # Update model options
        migrations.AlterModelOptions(
            name='projectscore',
            options={'ordering': ['-scored_at'], 'verbose_name': 'Project Score', 'verbose_name_plural': 'Project Scores'},
        ),
        migrations.AlterModelOptions(
            name='projectscoredetail',
            options={'ordering': ['project_score', 'criteria'], 'verbose_name': 'Project Score Detail', 'verbose_name_plural': 'Project Score Details'},
        ),
        
        # Remove fields that are no longer needed
        migrations.RemoveField(
            model_name='scoringnote',
            name='project_score',
        ),
        migrations.RemoveField(
            model_name='scoringrubricitem',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='scoringsettings',
            name='advisor_rubric',
        ),
        migrations.RemoveField(
            model_name='scoringsettings',
            name='committee_rubric',
        ),
        migrations.RemoveField(
            model_name='scoringrubric',
            name='rubric_type',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='evaluator',
        ),
        # migrations.RemoveField(
        #     model_name='projectscore',
        #     name='evaluator_id',
        # ),
        migrations.RemoveField(
            model_name='projectscore',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='projectscoredetail',
            name='comments',
        ),
        # migrations.RemoveField(
        #     model_name='projectscoredetail',
        #     name='rubric_item',
        # ),
        
        # Add new fields
        migrations.AddField(
            model_name='projectscore',
            name='scored_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectscore',
            name='scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectscore',
            name='scoring_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectscoredetail',
            name='max_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='projectscoredetail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectscoredetail',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoring.scoringcriteria'),
        ),
        migrations.AddField(
            model_name='scoringrubric',
            name='project_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        
        # Update existing fields
        migrations.AlterField(
            model_name='projectscore',
            name='max_possible_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.scoringrubric'),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='total_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='projectscoredetail',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        
        # Update unique constraints (do this after adding fields)
        migrations.AlterUniqueTogether(
            name='scoringsettings',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='projectscore',
            unique_together={('project_group', 'scorer', 'rubric')},
        ),
        migrations.AlterUniqueTogether(
            name='projectscoredetail',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectscoredetail',
            unique_together={('project_score', 'criteria')},
        ),
        
        # Delete old models
        migrations.DeleteModel(
            name='ScoringAudit',
        ),
        migrations.DeleteModel(
            name='ScoringNote',
        ),
        migrations.DeleteModel(
            name='ScoringSettings',
        ),
        migrations.DeleteModel(
            name='ScoringRubricItem',
        ),
    ]