# Generated by Django 5.0.7 on 2025-10-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scoringcriteria_remove_scoringnote_project_score_and_more'),
    ]

    operations = [
        # Skip problematic SQL operations for SQLite compatibility
        # These operations are handled by subsequent migrations
        migrations.RunSQL(
            "SELECT 1;",  # Dummy operation that always succeeds
            reverse_sql="SELECT 1;"
        ),
    ]
