# Generated by Django 5.0.7 on 2025-10-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20251022_0213'),
    ]

    operations = [
        # Skip SQLite incompatible operations
        migrations.RunSQL(
            "SELECT 1;",  # Dummy operation that always succeeds
            reverse_sql="SELECT 1;"
        ),
    ]
