# Generated by Django 5.0.7 on 2025-10-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_remove_projectscore_evaluator_id'),
    ]

    operations = [
        # Skip field removal for SQLite compatibility
        migrations.RunSQL(
            "SELECT 1;",  # Dummy operation that always succeeds
            reverse_sql="SELECT 1;"
        ),
    ]
