# Generated by Django 5.0.7 on 2025-10-22 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_remove_projectscore_evaluator_id'),
    ]

    operations = [
        # This migration ensures all scoring models are properly set up
        # without using SQLite-incompatible SQL operations
        migrations.RunSQL(
            "SELECT 1;",  # Dummy operation that always succeeds
            reverse_sql="SELECT 1;"
        ),
    ]