# Generated by Django 5.0.7 on 2025-10-22 04:30

from django.db import migrations, connection


def safely_remove_evaluator_id_field(apps, schema_editor):
    """Safely remove evaluator_id field if it exists."""
    with connection.cursor() as cursor:
        # Check database engine
        db_engine = connection.vendor
        
        if db_engine == 'sqlite':
            # SQLite check
            cursor.execute("PRAGMA table_info(project_scores)")
            columns = cursor.fetchall()
            column_exists = any(col[1] == 'evaluator_id' for col in columns)
            
            if column_exists:
                print("SQLite detected: evaluator_id column exists but cannot be removed safely")
                print("This migration will be skipped for SQLite")
            else:
                print("evaluator_id column does not exist in SQLite, skipping removal")
        else:
            # For PostgreSQL and other databases, use the standard Django operation
            print("Non-SQLite database detected, proceeding with field removal")


def reverse_safely_remove_evaluator_id_field(apps, schema_editor):
    """Reverse migration - this is a no-op since we're just removing a column."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_fix_evaluator_id_safely'),
    ]

    operations = [
        migrations.RunPython(
            safely_remove_evaluator_id_field,
            reverse_safely_remove_evaluator_id_field,
        ),
    ]
