# Generated by Django 5.0.7 on 2025-10-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_remove_projectscore_evaluator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectscore',
            name='evaluator_id',
        ),
    ]
