# Generated by Django 5.0.7 on 2025-10-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_id', models.CharField(max_length=50, unique=True)),
                ('quota', models.IntegerField(default=5)),
                ('main_committee_quota', models.IntegerField(default=5)),
                ('second_committee_quota', models.IntegerField(default=5)),
                ('third_committee_quota', models.IntegerField(default=5)),
                ('academic_title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('office_location', models.CharField(blank=True, max_length=200, null=True)),
                ('office_hours', models.TextField(blank=True, null=True)),
                ('phone_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_department_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advisor',
                'verbose_name_plural': 'Advisors',
                'db_table': 'advisors',
                'ordering': ['advisor_id'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('performance', 'Performance Note'), ('workload', 'Workload Note'), ('availability', 'Availability Note'), ('general', 'General Note')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='advisors.advisor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advisor Note',
                'verbose_name_plural': 'Advisor Notes',
                'db_table': 'advisor_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='advisors.advisor')),
            ],
            options={
                'verbose_name': 'Advisor Availability',
                'verbose_name_plural': 'Advisor Availability Records',
                'db_table': 'advisor_availability',
                'ordering': ['-date'],
                'unique_together': {('advisor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AdvisorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('projects_completed', models.IntegerField(default=0)),
                ('average_project_score', models.FloatField(default=0.0)),
                ('student_satisfaction_score', models.FloatField(default=0.0)),
                ('response_time_hours', models.FloatField(default=0.0)),
                ('on_time_completion_rate', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('innovation_score', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='advisors.advisor')),
            ],
            options={
                'verbose_name': 'Advisor Performance',
                'verbose_name_plural': 'Advisor Performance Records',
                'db_table': 'advisor_performance',
                'ordering': ['-academic_year'],
                'unique_together': {('advisor', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='AdvisorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=200)),
                ('expertise_level', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='advisors.advisor')),
            ],
            options={
                'verbose_name': 'Advisor Specialization',
                'verbose_name_plural': 'Advisor Specializations',
                'db_table': 'advisor_specializations',
                'unique_together': {('advisor', 'major')},
            },
        ),
        migrations.CreateModel(
            name='AdvisorWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=20)),
                ('supervising_projects', models.IntegerField(default=0)),
                ('main_committee_projects', models.IntegerField(default=0)),
                ('second_committee_projects', models.IntegerField(default=0)),
                ('third_committee_projects', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('supervising_capacity', models.IntegerField(default=5)),
                ('main_committee_capacity', models.IntegerField(default=5)),
                ('second_committee_capacity', models.IntegerField(default=5)),
                ('third_committee_capacity', models.IntegerField(default=5)),
                ('supervising_utilization', models.FloatField(default=0.0)),
                ('main_committee_utilization', models.FloatField(default=0.0)),
                ('second_committee_utilization', models.FloatField(default=0.0)),
                ('third_committee_utilization', models.FloatField(default=0.0)),
                ('overall_utilization', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_records', to='advisors.advisor')),
            ],
            options={
                'verbose_name': 'Advisor Workload',
                'verbose_name_plural': 'Advisor Workloads',
                'db_table': 'advisor_workloads',
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('advisor', 'academic_year', 'semester')},
            },
        ),
    ]
