# Generated by Django 5.0.7 on 2025-10-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='max_students',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='advisor',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
